// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/hero-section/VideoBackground.tsx": () => import("../components/mockups/hero-section/VideoBackground.tsx")
};
