"use client";
import SEOHead from "@/components/ui/seo-head";

import Navigation from "@/components/ui/navigation";
import MegaFooter from "@/components/ui/mega-footer";

export default function PrivacyPolicy() {
  return (
    <div className="min-h-screen bg-stone-50">
      <SEOHead 
        title="Privacy Policy | Business Builders"
        description="Business Builders privacy policy explaining how we collect, use, and protect your personal data when using our services."
        keywords="privacy policy, data protection, GDPR, Business Builders"
        canonicalUrl="https://businessbldrs.com/privacy-policy"
      />
      <Navigation />
      
      {/* Hero Section */}
      <section className="band-white pt-32 pb-16">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="text-center">
            <div className="inline-block px-4 py-2 bg-yellow-400 mb-6">
              <span className="label-industrial text-charcoal-900">BUSINESS BUILDERS</span>
            </div>
            <h1 className="headline-xl text-charcoal-900 mb-6">
              <span className="text-yellow-500">PRIVACY POLICY</span>
            </h1>
          </div>
        </div>
      </section>

      {/* Privacy Policy Content */}
      <section className="py-16 band-stone">
        <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="bento-card p-8 lg:p-12">
            
            <div className="mb-8">
              <p className="text-stone-500 text-lg mb-2"><strong className="text-charcoal-900">Effective date:</strong> August 26, 2019</p>
              <p className="text-stone-600 text-lg leading-relaxed">
                Business Builders ("us", "we", or "our") operates the https://businessbldrs.com website (hereinafter referred to as the "Service").
              </p>
              <p className="text-stone-600 text-lg leading-relaxed mt-4">
                This page informs you of our policies regarding the collection, use and disclosure of personal data when you use our Service and the choices you have associated with that data.
              </p>
              <p className="text-stone-600 text-lg leading-relaxed mt-4">
                We use your data to provide and improve the Service. By using the Service, you agree to the collection and use of information in accordance with this policy. Unless otherwise defined in this Privacy Policy, the terms used in this Privacy Policy have the same meanings as in our Terms and Conditions, accessible from https://businessbldrs.com
              </p>
            </div>

            {/* Definitions Section */}
            <div className="mb-10">
              <h2 className="headline-md text-yellow-400 mb-6">Definitions</h2>
              
              <div className="space-y-6">
                <div>
                  <h3 className="text-xl font-display font-bold uppercase text-charcoal-900 mb-2">Service</h3>
                  <p className="text-stone-600">Service is the https://businessbldrs.com website operated by Business Builders</p>
                </div>
                
                <div>
                  <h3 className="text-xl font-display font-bold uppercase text-charcoal-900 mb-2">Personal Data</h3>
                  <p className="text-stone-600">Personal Data means data about a living individual who can be identified from those data (or from those and other information either in our possession or likely to come into our possession).</p>
                </div>
                
                <div>
                  <h3 className="text-xl font-display font-bold uppercase text-charcoal-900 mb-2">Usage Data</h3>
                  <p className="text-stone-600">Usage Data is data collected automatically either generated by the use of the Service or from the Service infrastructure itself (for example, the duration of a page visit).</p>
                </div>
                
                <div>
                  <h3 className="text-xl font-display font-bold uppercase text-charcoal-900 mb-2">Cookies</h3>
                  <p className="text-stone-600">Cookies are small files stored on your device (computer or mobile device).</p>
                </div>
                
                <div>
                  <h3 className="text-xl font-display font-bold uppercase text-charcoal-900 mb-2">Data Controller</h3>
                  <p className="text-stone-600">Data Controller means the natural or legal person who (either alone or jointly or in common with other persons) determines the purposes for which and the manner in which any personal information are, or are to be, processed.</p>
                  <p className="text-stone-600 mt-2">For the purpose of this Privacy Policy, we are a Data Controller of your Personal Data.</p>
                </div>
                
                <div>
                  <h3 className="text-xl font-display font-bold uppercase text-charcoal-900 mb-2">Data Processors (or Service Providers)</h3>
                  <p className="text-stone-600">Data Processor (or Service Provider) means any natural or legal person who processes the data on behalf of the Data Controller.</p>
                  <p className="text-stone-600 mt-2">We may use the services of various Service Providers in order to process your data more effectively.</p>
                </div>
                
                <div>
                  <h3 className="text-xl font-display font-bold uppercase text-charcoal-900 mb-2">Data Subject (or User)</h3>
                  <p className="text-stone-600">Data Subject is any living individual who is using our Service and is the subject of Personal Data.</p>
                </div>
              </div>
            </div>

            {/* Information Collection Section */}
            <div className="mb-10">
              <h2 className="headline-md text-yellow-400 mb-6">Information Collection and Use</h2>
              <p className="text-stone-600 text-lg leading-relaxed mb-6">
                We collect several different types of information for various purposes to provide and improve our Service to you.
              </p>
              
              <h3 className="text-2xl font-display font-bold uppercase text-charcoal-900 mb-4">Types of Data Collected</h3>
              
              <div className="mb-6">
                <h4 className="text-xl font-display font-bold uppercase text-charcoal-900 mb-3">Personal Data</h4>
                <p className="text-stone-600 mb-4">
                  While using our Service, we may ask you to provide us with certain personally identifiable information that can be used to contact or identify you ("Personal Data"). Personally identifiable information may include, but is not limited to:
                </p>
                <ul className="list-disc list-inside text-stone-600 space-y-2 ml-4">
                  <li>Email address</li>
                  <li>First name and last name</li>
                  <li>Phone number</li>
                  <li>Cookies and Usage Data</li>
                </ul>
                <p className="text-stone-600 mt-4">
                  We may use your Personal Data to contact you with newsletters, marketing or promotional materials and other information that may be of interest to you. You may opt out of receiving any, or all, of these communications from us by following the unsubscribe link or the instructions provided in any email we send.
                </p>
              </div>
              
              <div className="mb-6">
                <h4 className="text-xl font-display font-bold uppercase text-charcoal-900 mb-3">Usage Data</h4>
                <p className="text-stone-600">
                  We may also collect information on how the Service is accessed and used ("Usage Data"). This Usage Data may include information such as your computer's Internet Protocol address (e.g. IP address), browser type, browser version, the pages of our Service that you visit, the time and date of your visit, the time spent on those pages, unique device identifiers and other diagnostic data.
                </p>
              </div>
              
              <div className="mb-6">
                <h4 className="text-xl font-display font-bold uppercase text-charcoal-900 mb-3">Tracking & Cookies Data</h4>
                <p className="text-stone-600 mb-4">
                  We use cookies and similar tracking technologies to track the activity on our Service and we hold certain information.
                </p>
                <p className="text-stone-600 mb-4">
                  Cookies are files with a small amount of data which may include an anonymous unique identifier. Cookies are sent to your browser from a website and stored on your device. Other tracking technologies are also used such as beacons, tags and scripts to collect and track information and to improve and analyse our Service.
                </p>
                <p className="text-stone-600 mb-4">
                  You can instruct your browser to refuse all cookies or to indicate when a cookie is being sent. However, if you do not accept cookies, you may not be able to use some portions of our Service.
                </p>
                <p className="text-stone-600 mb-2">Examples of Cookies we use:</p>
                <ul className="list-disc list-inside text-stone-600 space-y-2 ml-4">
                  <li><strong>Session Cookies.</strong> We use Session Cookies to operate our Service.</li>
                  <li><strong>Preference Cookies.</strong> We use Preference Cookies to remember your preferences and various settings.</li>
                  <li><strong>Security Cookies.</strong> We use Security Cookies for security purposes.</li>
                </ul>
              </div>
            </div>

            {/* Use of Data Section */}
            <div className="mb-10">
              <h2 className="headline-md text-yellow-400 mb-6">Use of Data</h2>
              <p className="text-stone-600 mb-4">Business Builders uses the collected data for various purposes:</p>
              <ul className="list-disc list-inside text-stone-600 space-y-2 ml-4">
                <li>To provide and maintain our Service</li>
                <li>To notify you about changes to our Service</li>
                <li>To allow you to participate in interactive features of our Service when you choose to do so</li>
                <li>To provide customer support</li>
                <li>To gather analysis or valuable information so that we can improve our Service</li>
                <li>To monitor the usage of our Service</li>
                <li>To detect, prevent and address technical issues</li>
                <li>To provide you with news, special offers and general information about other goods, services and events which we offer that are similar to those that you have already purchased or enquired about unless you have opted not to receive such information</li>
              </ul>
            </div>

            {/* GDPR Section */}
            <div className="mb-10">
              <h2 className="headline-md text-yellow-400 mb-6">Legal Basis for Processing Personal Data under GDPR</h2>
              <p className="text-stone-600 mb-4">
                If you are from the European Economic Area (EEA), Business Builders legal basis for collecting and using the personal information described in this Privacy Policy depends on the Personal Data we collect and the specific context in which we collect it.
              </p>
              <p className="text-stone-600 mb-4">Business Builders may process your Personal Data because:</p>
              <ul className="list-disc list-inside text-stone-600 space-y-2 ml-4">
                <li>We need to perform a contract with you</li>
                <li>You have given us permission to do so</li>
                <li>The processing is in our legitimate interests and it is not overridden by your rights</li>
                <li>To comply with the law</li>
              </ul>
            </div>

            {/* Data Rights Section */}
            <div className="mb-10">
              <h2 className="headline-md text-yellow-400 mb-6">Your Data Protection Rights under GDPR</h2>
              <p className="text-stone-600 mb-4">
                If you are a resident of the European Economic Area (EEA), you have certain data protection rights. Business Builders aims to take reasonable steps to allow you to correct, amend, delete or limit the use of your Personal Data.
              </p>
              <p className="text-stone-600 mb-4">
                If you wish to be informed about what Personal Data we hold about you and if you want it to be removed from our systems, please contact us.
              </p>
              <p className="text-stone-600 mb-4">In certain circumstances, you have the following data protection rights:</p>
              <ul className="list-disc list-inside text-stone-600 space-y-3 ml-4">
                <li><strong>The right to access, update or delete the information we have on you.</strong> Whenever made possible, you can access, update or request deletion of your Personal Data directly within your account settings section. If you are unable to perform these actions yourself, please contact us to assist you.</li>
                <li><strong>The right of rectification.</strong> You have the right to have your information rectified if that information is inaccurate or incomplete.</li>
                <li><strong>The right to object.</strong> You have the right to object to our processing of your Personal Data.</li>
                <li><strong>The right of restriction.</strong> You have the right to request that we restrict the processing of your personal information.</li>
                <li><strong>The right to data portability.</strong> You have the right to be provided with a copy of the information we have on you in a structured, machine-readable and commonly used format.</li>
                <li><strong>The right to withdraw consent.</strong> You also have the right to withdraw your consent at any time where Business Builders relied on your consent to process your personal information.</li>
              </ul>
              <p className="text-stone-600 mt-4">
                Please note that we may ask you to verify your identity before responding to such requests.
              </p>
            </div>

            {/* Contact Section */}
            <div className="mb-10">
              <h2 className="headline-md text-yellow-400 mb-6">Contact Us</h2>
              <p className="text-stone-600 mb-4">If you have any questions about this Privacy Policy, please contact us:</p>
              <div className="bg-stone-100 p-6 border-2 border-charcoal-800 shadow-offset">
                <p className="text-stone-600 mb-2"><strong className="text-charcoal-900">By email:</strong> info@businessbldrs.com</p>
                <p className="text-stone-600 mb-2"><strong className="text-charcoal-900">Address:</strong></p>
                <p className="text-stone-600 mb-1">701 Market Street, Unit 101</p>
                <p className="text-stone-600 mb-4">St. Augustine, FL 32095</p>
                <p className="text-stone-600"><strong className="text-charcoal-900">Phone:</strong> <a href="tel:877-378-6101" className="text-yellow-600 hover:text-yellow-500 font-semibold">(877) 378-6101</a></p>
              </div>
            </div>

            {/* Additional Sections */}
            <div className="space-y-8 text-stone-600">
              <div>
                <h3 className="text-2xl font-display font-bold uppercase text-charcoal-900 mb-4">Security of Data</h3>
                <p>The security of your data is important to us but remember that no method of transmission over the Internet or method of electronic storage is 100% secure. While we strive to use commercially acceptable means to protect your Personal Data, we cannot guarantee its absolute security.</p>
              </div>
              
              <div>
                <h3 className="text-2xl font-display font-bold uppercase text-charcoal-900 mb-4">Children's Privacy</h3>
                <p>Our Service does not address anyone under the age of 18 ("Children"). We do not knowingly collect personally identifiable information from anyone under the age of 18. If you are a parent or guardian and you are aware that your Child has provided us with Personal Data, please contact us.</p>
              </div>
              
              <div>
                <h3 className="text-2xl font-display font-bold uppercase text-charcoal-900 mb-4">Changes to This Privacy Policy</h3>
                <p>We may update our Privacy Policy from time to time. We will notify you of any changes by posting the new Privacy Policy on this page. You are advised to review this Privacy Policy periodically for any changes. Changes to this Privacy Policy are effective when they are posted on this page.</p>
              </div>
            </div>

          </div>
        </div>
      </section>

      <MegaFooter />
    </div>
  );
}
